AllCops:
  NewCops: enable
  SuggestExtensions: false

Gemspec/DevelopmentDependencies:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

Metrics/ClassLength:
  Exclude:
    - 'lib/zadarma/client.rb'
